[package]
name = "huesos-hxfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
writer = []
crypto-aes = ["dep:aes", "dep:cipher"]
crypto-aes-gcm = ["dep:aes-gcm", "dep:hkdf", "dep:sha2", "aes-gcm/aes", "aes-gcm/alloc"]
compression-engines = ["dep:lz4_flex"]
page-cache = []

[dependencies]
huesos-abi = { path = "../huesos-abi" }
aes = { version = "0.8", default-features = false, optional = true }
cipher = { version = "0.4", default-features = false, optional = true }
aes-gcm = { version = "0.10", default-features = false, optional = true }
hkdf = { version = "0.12", default-features = false, optional = true }
sha2 = { version = "0.10", default-features = false, optional = true }
lz4_flex = { version = "0.11", default-features = false, optional = true }
