[build]
target = "../x86_64-huesos-userspace.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-huesos-userspace]
rustflags = ["-C", "link-arg=-T../user_linker.ld"]
