#!/usr/bin/env python3
"""Convert Cozette BDF to a Rust bitmap-font array.

Extracts ASCII 0x20..0x7E from a BDF file and emits a
`pub const FONT_6X13: [[u8; 13]; 95]` array. Each glyph is 13 rows
tall; each row holds 6 pixels in the low 6 bits (LSB = leftmost).

This matches the layout used by libcanvas::font8x8::FONT_8X8 (bit 0
LSB = leftmost pixel), so the caller-side render loop only needs the
new width/height constants.
"""
import sys
import re
from pathlib import Path


def parse_bdf(path):
    glyphs = {}
    with open(path) as f:
        it = iter(f)
        char = None
        for line in it:
            line = line.rstrip("\n")
            if line.startswith("STARTCHAR"):
                char = {"name": line.split(None, 1)[1] if " " in line else "", "bitmap": []}
            elif line.startswith("ENCODING"):
                if char is not None:
                    char["encoding"] = int(line.split()[1])
            elif line.startswith("BBX"):
                _, w, h, ox, oy = line.split()
                char["bbx_w"] = int(w)
                char["bbx_h"] = int(h)
                char["bbx_ox"] = int(ox)
                char["bbx_oy"] = int(oy)
            elif line.startswith("DWIDTH"):
                _, dw, _dh = line.split()
                char["dwidth"] = int(dw)
            elif line == "BITMAP":
                for hex_line in it:
                    hex_line = hex_line.rstrip("\n")
                    if hex_line == "ENDCHAR":
                        break
                    char["bitmap"].append(int(hex_line, 16))
                enc = char.get("encoding")
                if enc is not None:
                    glyphs[enc] = char
                char = None
    return glyphs


# Cozette cell metrics:
# * DWIDTH = 6 (advance width)
# * Ascent above baseline in the FONT: ~10; descent ~3
# * Cell height = 13 (10 above + 3 below)
# We render into a 6-wide × 13-tall cell. The BDF's baseline is at
# ROW_ASCENT (0-indexed from top). BBX (w, h, ox, oy) gives the
# glyph's local bounding box: ox = pixels right of cell's left edge,
# oy = pixels above baseline (so bottom of glyph is at ROW_ASCENT - oy).
CELL_W = 6
CELL_H = 13
ROW_ASCENT = 10  # baseline row index (0-indexed from top)


def to_rows(glyph):
    """Return 13 bytes; each holds up to 6 pixels in LSB=leftmost order."""
    rows = [0] * CELL_H
    bbx_w = glyph.get("bbx_w", 0)
    bbx_h = glyph.get("bbx_h", 0)
    bbx_ox = glyph.get("bbx_ox", 0)
    bbx_oy = glyph.get("bbx_oy", 0)
    bitmap = glyph.get("bitmap", [])
    if bbx_w == 0 or bbx_h == 0 or not bitmap:
        return rows
    # BDF byte packing: MSB = leftmost pixel of each BBX row; rows are
    # padded to a whole byte. The BBX has bbx_h rows.
    # First BBX row is topmost row of the glyph's local box; its
    # y-position in the cell is ROW_ASCENT - (bbx_oy + bbx_h - 1) - 1
    # + row_index. Simpler: cell_y_top_of_bbx = ROW_ASCENT - bbx_oy - bbx_h.
    cell_y_top = ROW_ASCENT - bbx_oy - bbx_h
    for r in range(min(bbx_h, len(bitmap))):
        cell_y = cell_y_top + r
        if cell_y < 0 or cell_y >= CELL_H:
            continue
        row_bits = bitmap[r]
        # row_bits is MSB-first; drop padding beyond bbx_w.
        # Byte(s) per row = ceil(bbx_w / 8).
        # cozette max glyph width = 5, so single byte per row.
        byte_bits = (len(bin(row_bits)) - 2 + 7) & ~7  # never used; row is fixed 8 bits
        _ = byte_bits
        out = 0
        for px in range(bbx_w):
            # bit index in source (from MSB of byte 0):
            src_bit = 7 - (px % 8)
            # We only handle single-byte rows (max width 5). If cozette
            # ever ships wider glyphs we'd need to walk more bytes.
            if bbx_w > 8:
                raise SystemExit(f"glyph too wide ({bbx_w}) for single-byte row")
            if (row_bits >> src_bit) & 1:
                cell_x = bbx_ox + px
                if 0 <= cell_x < CELL_W:
                    out |= 1 << cell_x  # LSB = leftmost
        rows[cell_y] = out
    return rows


def emit_rust(glyphs, out_path):
    lines = [
        "//! Cozette bitmap font, 6x13 monochrome, ASCII 0x20..0x7E.",
        "//!",
        "//! Source: https://github.com/slavfox/Cozette (MIT license).",
        "//! Regenerated by `tools/bdf2rs.py`; do not hand-edit the FONT_6X13",
        "//! array — regenerate from the upstream `.bdf` release instead.",
        "//!",
        "//! Cell layout: 6 pixels wide × 13 pixels tall. Each row is a `u8`",
        "//! where bit 0 (LSB) is the leftmost pixel and bit 5 is the",
        "//! rightmost visible pixel; bits 6-7 are always zero.",
        "//!",
        "//! Cozette is intentionally denser than the previous 8x8 DejaVu",
        "//! font, and ships proper baseline / descender rows, which is",
        "//! why the cell is 13 rows tall despite the widest glyph being",
        "//! ~5 pixels: rows 0-2 are ascender/accent space, rows 3-9 are",
        "//! the main x-height, row 10 is the baseline, rows 11-12 are the",
        "//! descender area used by 'g', 'p', 'y', etc.",
        "",
        "/// Cell width in pixels (advance width). Callers that laid out",
        "/// text against `FONT_8X8` should switch to this constant to keep",
        "/// their code portable across font swaps.",
        "pub const CELL_W: usize = 6;",
        "",
        "/// Cell height in pixels.",
        "pub const CELL_H: usize = 13;",
        "",
        "#[rustfmt::skip]",
        "pub const FONT_6X13: [[u8; 13]; 95] = [",
    ]
    for code in range(0x20, 0x7F):
        glyph = glyphs.get(code)
        if glyph is None:
            rows = [0] * CELL_H
            name = f"missing 0x{code:02x}"
        else:
            rows = to_rows(glyph)
            ch = chr(code)
            if ch in {"'", "\\"}:
                # Not needed since we use single-char label, escape if used later.
                name = ch
            else:
                name = ch
        row_bytes = ", ".join(f"0b{r:08b}" for r in rows)
        lines.append(
            f"    [{row_bytes}], // 0x{code:02x} '{name}'"
            if name and name.isprintable() and name != "'" and name != "\\"
            else f"    [{row_bytes}], // 0x{code:02x}"
        )
    lines.append("];")
    lines.append("")
    Path(out_path).write_text("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: bdf2rs.py IN.bdf OUT.rs", file=sys.stderr)
        sys.exit(2)
    glyphs = parse_bdf(sys.argv[1])
    emit_rust(glyphs, sys.argv[2])
    print(f"wrote {sys.argv[2]}: {sum(1 for c in range(0x20, 0x7F) if c in glyphs)} glyphs")
