[package]
name = "huesos-key-broker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "huesos-key-broker"
path = "src/main.rs"

[dependencies]
libcanvas = { path = "../libcanvas" }
huesos-abi = { path = "../../huesos-abi" }

[features]
default = []
fail-after-first-grant = []

[profile.release]
opt-level = 2
panic = "abort"
lto = false

[profile.dev]
panic = "abort"

[workspace]
